apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-rest-deployment
  labels:
    app: hello-world-rest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-rest
  template:
    metadata:
      labels:
        app: hello-world-rest
    spec:
      containers:
      - name: hello-world-rest
        image: vad1mo/hello-world-rest
        ports:
        - containerPort: 80
