apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-rest
  labels:
    app: hello-world-rest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-rest
  template:
    metadata:
      labels:
        app: hello-world-rest
    spec:
      containers:
      - name: hello-world-rest
        image: vad1mo/hello-world-rest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5050
        volumeMounts:
        - mountPath: /log
          name: data
      volumes:
       - name: data
         persistentVolumeClaim:
          claimName: my-test-pvc  
