apiVersion: v1
kind: Service
metadata:
  name: hello-world-rest
spec:
  ports:
    - targetPort: 5050
      nodePort: 31000 
      port: 5050          
  type:  NodePort
  selector:    
      app: hello-world-rest
      