apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  ports:
    
    - targetPort: 5050
      nodePort: 31000 
      port: 5050
      
    
  type:  nodePort
  selector:
    
      name: simple-webapp
      type: NodePort